import React from "react";
import { Route, Routes } from "react-router";
import { Capitulos36 } from "../Components/elements/Animes36";

export default function Routes36() {
  return (
    <Routes>
      <Route
        path="/karakuri-circus"
        element={
          <Capitulos36
            descripcion={
              "El protagonista, Masaru, acaba de heredar una gran fortuna tras la muerte de su padre. Sin embargo, la gente está tratando de ponerlo en sus manos por cualquier medio necesario, incluso si eso significa matarlo. Narumi ayuda a Masaru a ser secuestrado después de luchar contra figuras extrañas. Descubre que no son humanos, sino títeres de madera con una fuerza increíble. Después de una dura lucha, Narumi se ve obligado a admitir que no es un oponente para ellos; y justo cuando empieza a pensar que Masaru será capturado, Shirogane, el vigilante de Masaru, llega de Francia con un arma, el títere Arlequin. Aquí comienza la historia de Karakuri Circus."
            }
            anime={"Karakuri Circus"}
            tipo={"TV"}
            numeroEpisodios={"36"}
            estado={"Finalizado"}
            imagenAnime={"https://i.postimg.cc/VNf018f3/karakuri-circus.jpg"}
            capituloAnime1={"/ver/karakuri-circus-1"}
            capituloAnime2={"/ver/karakuri-circus-2"}
            capituloAnime3={"/ver/karakuri-circus-3"}
            capituloAnime4={"/ver/karakuri-circus-4"}
            capituloAnime5={"/ver/karakuri-circus-5"}
            capituloAnime6={"/ver/karakuri-circus-6"}
            capituloAnime7={"/ver/karakuri-circus-7"}
            capituloAnime8={"/ver/karakuri-circus-8"}
            capituloAnime9={"/ver/karakuri-circus-9"}
            capituloAnime10={"/ver/karakuri-circus-10"}
            capituloAnime11={"/ver/karakuri-circus-11"}
            capituloAnime12={"/ver/karakuri-circus-12"}
            capituloAnime13={"/ver/karakuri-circus-13"}
            capituloAnime14={"/ver/karakuri-circus-14"}
            capituloAnime15={"/ver/karakuri-circus-15"}
            capituloAnime16={"/ver/karakuri-circus-16"}
            capituloAnime17={"/ver/karakuri-circus-17"}
            capituloAnime18={"/ver/karakuri-circus-18"}
            capituloAnime19={"/ver/karakuri-circus-19"}
            capituloAnime20={"/ver/karakuri-circus-20"}
            capituloAnime21={"/ver/karakuri-circus-21"}
            capituloAnime22={"/ver/karakuri-circus-22"}
            capituloAnime23={"/ver/karakuri-circus-23"}
            capituloAnime24={"/ver/karakuri-circus-24"}
            capituloAnime25={"/ver/karakuri-circus-25"}
            capituloAnime26={"/ver/karakuri-circus-26"}
            capituloAnime27={"/ver/karakuri-circus-27"}
            capituloAnime28={"/ver/karakuri-circus-28"}
            capituloAnime29={"/ver/karakuri-circus-29"}
            capituloAnime30={"/ver/karakuri-circus-30"}
            capituloAnime31={"/ver/karakuri-circus-31"}
            capituloAnime32={"/ver/karakuri-circus-32"}
            capituloAnime33={"/ver/karakuri-circus-33"}
            capituloAnime34={"/ver/karakuri-circus-34"}
            capituloAnime35={"/ver/karakuri-circus-35"}
            capituloAnime36={"/ver/karakuri-circus-36"}
            sec1={"disable"}
            sec2={"disable"}
            sec3={"disable"}
          />
        }
      />
      <Route
        path="/bungou-stray-dogs-4ta-temporada"
        element={
          <Capitulos36
            descripcion={"Cuarta temporada de Bungou Stray Dogs"}
            anime={"Bungou Stray Dogs"}
            tipo={"TV"}
            numeroEpisodios={"1"}
            estado={"En Emision"}
            imagenAnime={"https://i.postimg.cc/8PvHxKnk/Stray-dogs.jpg"}
            capituloAnime1={"/ver/bungou-stray-dogs-4ta-temporada-1"}
            li2="disable"
            li3="disable"
            li4="disable"
            li5="disable"
            li6="disable"
            li7="disable"
            li8="disable"
            li9="disable"
            li10="disable"
            li11="disable"
            li12="disable"
            li13="disable"
            li14="disable"
            li15="disable"
            li16="disable"
            li17="disable"
            li18="disable"
            li19="disable"
            li20="disable"
            li21="disable"
            li22="disable"
            li23="disable"
            li24="disable"
            li25="disable"
            li26="disable"
            li27="disable"
            li28="disable"
            li29="disable"
            li30="disable"
            li31="disable"
            li32="disable"
            li33="disable"
            li34="disable"
            li35="disable"
            li36="disable"
            sec1={"disable"}
            sec2={"disable"}
            sec3={"disable"}
          />
        }
      />
      <Route
        path="/karakuri-circus"
        element={
          <Capitulos36
            descripcion={
              "El protagonista, Masaru, acaba de heredar una gran fortuna tras la muerte de su padre. Sin embargo, la gente está tratando de ponerlo en sus manos por cualquier medio necesario, incluso si eso significa matarlo. Narumi ayuda a Masaru a ser secuestrado después de luchar contra figuras extrañas. Descubre que no son humanos, sino títeres de madera con una fuerza increíble. Después de una dura lucha, Narumi se ve obligado a admitir que no es un oponente para ellos; y justo cuando empieza a pensar que Masaru será capturado, Shirogane, el vigilante de Masaru, llega de Francia con un arma, el títere Arlequin. Aquí comienza la historia de Karakuri Circus."
            }
            anime={"Karakuri Circus"}
            tipo={"TV"}
            numeroEpisodios={"36"}
            estado={"Finalizado"}
            imagenAnime={"https://i.postimg.cc/VNf018f3/karakuri-circus.jpg"}
            capituloAnime1={"/ver/karakuri-circus-1"}
            capituloAnime2={"/ver/karakuri-circus-2"}
            capituloAnime3={"/ver/karakuri-circus-3"}
            capituloAnime4={"/ver/karakuri-circus-4"}
            capituloAnime5={"/ver/karakuri-circus-5"}
            capituloAnime6={"/ver/karakuri-circus-6"}
            capituloAnime7={"/ver/karakuri-circus-7"}
            capituloAnime8={"/ver/karakuri-circus-8"}
            capituloAnime9={"/ver/karakuri-circus-9"}
            capituloAnime10={"/ver/karakuri-circus-10"}
            capituloAnime11={"/ver/karakuri-circus-11"}
            capituloAnime12={"/ver/karakuri-circus-12"}
            capituloAnime13={"/ver/karakuri-circus-13"}
            capituloAnime14={"/ver/karakuri-circus-14"}
            capituloAnime15={"/ver/karakuri-circus-15"}
            capituloAnime16={"/ver/karakuri-circus-16"}
            capituloAnime17={"/ver/karakuri-circus-17"}
            capituloAnime18={"/ver/karakuri-circus-18"}
            capituloAnime19={"/ver/karakuri-circus-19"}
            capituloAnime20={"/ver/karakuri-circus-20"}
            capituloAnime21={"/ver/karakuri-circus-21"}
            capituloAnime22={"/ver/karakuri-circus-22"}
            capituloAnime23={"/ver/karakuri-circus-23"}
            capituloAnime24={"/ver/karakuri-circus-24"}
            capituloAnime25={"/ver/karakuri-circus-25"}
            capituloAnime26={"/ver/karakuri-circus-26"}
            capituloAnime27={"/ver/karakuri-circus-27"}
            capituloAnime28={"/ver/karakuri-circus-28"}
            capituloAnime29={"/ver/karakuri-circus-29"}
            capituloAnime30={"/ver/karakuri-circus-30"}
            capituloAnime31={"/ver/karakuri-circus-31"}
            capituloAnime32={"/ver/karakuri-circus-32"}
            capituloAnime33={"/ver/karakuri-circus-33"}
            capituloAnime34={"/ver/karakuri-circus-34"}
            capituloAnime35={"/ver/karakuri-circus-35"}
            capituloAnime36={"/ver/karakuri-circus-36"}
          />
        }
      />
    </Routes>
  );
}
